archive_path: ~/demo-archive-less
db_path: ~/clams-galaxy-export
apps:
  audio-segmenter:
    enabled: True
    repository: https://github.com/clamsproject/app-audio-segmenter.git
    description: "Audio segmentation based on acoustic classifier"
    type: Audio
  puakaldi:
    enabled: True
    repository: https://github.com/clamsproject/app-puakaldi-wrapper.git
    branch: develop
    description: "PopUp Archive Kaldi ASR"
    type: Audio,Alignment
  slatedetection:
    enabled: True
    repository: https://github.com/clamsproject/app-slatedetection.git
    description: "Slate detector"
    type: Video
  bardetection:
    enabled: True
    repository: https://github.com/clamsproject/app-barsdetection.git
    description: "SMPTE color bar detector"
    type: Video
  spacy-nlp:
    enabled: True
    repository: https://github.com/clamsproject/app-spacy-nlp.git
    description: "SpaCy Text Analyzer"
    type: Text
consumers:
  mmif-visualizer:
    enabled: True
    repository: https://github.com/clamsproject/mmif-visualizer.git
    description: "Display MMIF annotations"
